# Generated by Django 5.0.14 on 2026-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('license', models.CharField(db_index=True, max_length=50, unique=True)),
                ('safety_score', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('On Duty', 'On Duty'), ('Active', 'Active'), ('Off Duty', 'Off Duty'), ('Sick', 'Sick')], default='Active', max_length=20)),
                ('hours', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar_color', models.CharField(default='bg-indigo-600', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('license_category', models.CharField(blank=True, max_length=50, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=30, null=True)),
                ('total_distance', models.IntegerField(default=0)),
                ('fuel_efficiency', models.CharField(blank=True, max_length=30, null=True)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('recent_activity', models.JSONField(blank=True, default=list)),
                ('performance_timeline', models.JSONField(blank=True, default=list)),
                ('upcoming_trips_count', models.IntegerField(default=0)),
                ('today_distance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status'], name='drivers_dri_status_d7a5f5_idx'), models.Index(fields=['license'], name='drivers_dri_license_7552d4_idx')],
            },
        ),
    ]
