# Generated by Django 5.0.14 on 2026-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Fuel', 'Fuel'), ('Maintenance', 'Maintenance'), ('Driver Salary', 'Driver Salary'), ('Insurance', 'Insurance'), ('Tolls & Permits', 'Tolls & Permits'), ('Other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('reference', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'id'],
                'indexes': [models.Index(fields=['category'], name='expenses_ex_categor_fcaba7_idx'), models.Index(fields=['date'], name='expenses_ex_date_17a2b2_idx')],
            },
        ),
    ]
