# Generated by Django 5.0.14 on 2026-07-12 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=150)),
                ('departure', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Loading', 'Loading'), ('On Route', 'On Route'), ('Delayed', 'Delayed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('eta', models.CharField(max_length=100)),
                ('progress', models.IntegerField(default=0)),
                ('freight', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', 'id'],
                'indexes': [models.Index(fields=['status'], name='trips_trip_status_259ca6_idx'), models.Index(fields=['date'], name='trips_trip_date_23da48_idx')],
            },
        ),
    ]
