# Generated by Django 5.0.14 on 2026-07-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='eta',
            field=models.CharField(blank=True, default='TBD', max_length=100, null=True),
        ),
    ]
