# Generated by Django 5.0.14 on 2026-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('plate', models.CharField(db_index=True, max_length=30, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Service', 'In Service'), ('Maintenance', 'Maintenance'), ('Idle', 'Idle')], default='Active', max_length=20)),
                ('fuel', models.IntegerField(default=100)),
                ('health', models.IntegerField(default=100)),
                ('capacity', models.CharField(max_length=50)),
                ('last_service', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status'], name='vehicles_ve_status_f71f77_idx'), models.Index(fields=['plate'], name='vehicles_ve_plate_f1ecfa_idx')],
            },
        ),
    ]
