# Generated by Django 5.0.14 on 2026-07-12 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Critical', 'Critical')], default='Medium', max_length=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('technician', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', 'id'],
                'indexes': [models.Index(fields=['status'], name='maintenance_status_4bd260_idx'), models.Index(fields=['priority'], name='maintenance_priorit_a6bd12_idx')],
            },
        ),
    ]
